\" Manpage for adva_sdcard_smart_get
.TH ADVA_SDCARD_SMART_GET 8 "2021-09-10" "adva_sdcard-1.0.0" "Advamation SD-card tools"
.SH NAME
adva_sdcard_smart_get - get raw SMART-information from microSD-/SD-card
.SH SYNOPSIS
\fBadva_sdcard_smart_get\fR \fIDEVICE\fR
.SH DESCRIPTION
Get raw SMART-information from industrial microSD-/SD-card.
.br
For details, see adva-sdcard/README.
.PP
Note that this does not work with USB-cardreaders.
.PP
Supported cards:
.in +4n
.EX
\- Apacer CV110\-MSD / AK6.112*
\- Apacer CH110\-MSD / AK6.118*
\- Apacer H1\-M  / AP\-*\-1HTM
\- Apacer H2\-M  / AP\-*\-1RTM
\- Apacer H1\-SL / AP\-*\-2HTM
\- Apacer H2\-SL / AP\-*\-2RTM
\- Transcend 230I
\- Transcend 240I
.EE
.in
.SH OPTIONS
.TP
.I DEVICE
(micro)SD-card device, usually /dev/mmcblk0
.SH EXIT STATUS
.EX
0:     success
255:   invalid commandline-parameters
other: errno of the error
.EE
.SH EXAMPLES
adva_sdcard_smart_get /dev/mmcblk0
.SH AUTHORS
Advamation / Roland Freikamp <support@advamation.de>
.SH SEE ALSO
.BR adva_scard_smart (8),
.BR adva_sdcard_info (8),
adva-sdcard/README
