\" Manpage for adva-sdcard-info
.TH ADVA-SDCARD-INFO 8 "2025-03-17" "adva-sdcard-1.2.0" "Advamation SD-card tools"
.SH NAME
adva-sdcard-info \- get/parse microSD-/SD-card-information
.SH SYNOPSIS
\fBadva-sdcard-info\fR [\fB\-h\fR] [\fB\-p\fR | \fB\-j\fR] [\fB\-d\fR \fIDEVICE\fR] [\fB\-\-version\fR] [\fIcid\fR]
.SH DESCRIPTION
Get/parse microSD\-/SD\-card\-information from mmc\-device.
.br
For details, see adva-sdcard/README.md.
.PP
Note that this does not work with USB\-cardreaders.
.SH OPTIONS
.SS "positional arguments:"
.TP
.I cid
CID as hex string or file containing the CID, or - for stdin
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit.
.TP
\fB\-p\fR, \fB\-\-parsable\fR
Print output in parsable format.
.TP
\fB\-j\fR, \fB\-\-json\fR
Print output in JSON format.
.TP
\fB\-d\fR \fIDEVICE\fR, \fB\-\-device\fR \fIDEVICE\fR
Retrieve CID directly from SD\-card.
.TP
.B \-\-version
Show program's version number and exit.
.SH EXIT STATUS
.EX
0:   success
2:   invalid commandline-parameters
19:  device not found (ENODEV)
5:   cannot read from device (EIO)
22:  invalid CID data (EINVAL)
130: aborted (e.g. via Ctrl-C) (ECONNABORTED)
.EE
.SH EXAMPLES
adva-sdcard-info 275048415...
.br
adva-sdcard-info -d /dev/mmcblk0
.SH AUTHORS
Advamation / Roland Freikamp <support@advamation.de>
.SH SEE ALSO
.BR adva-scard-smart (8),
.BR adva-sdcard-smart-get (8),
adva-sdcard/README.md
