\" Manpage for adva-sdcard-smart-get
.TH ADVA-SDCARD-SMART-GET 8 "2025-03-17" "adva-sdcard-1.2.0" "Advamation SD-card tools"
.SH NAME
adva-sdcard-smart-get - get raw SMART-information from microSD-/SD-card
.SH SYNOPSIS
\fBadva-sdcard-smart-get\fR \fIDEVICE\fR
.SH DESCRIPTION
Get raw SMART-information from industrial microSD-/SD-card.
.br
For details, see adva-sdcard/README.md.
.PP
Note that this does not work with USB-cardreaders.
.PP
Supported cards:
.in +4n
.EX
\- Transcend 240I
\- Transcend 230I
\- Apacer CH110\-MSD / AK6.118*
\- Apacer CV110\-MSD / AK6.112*
\- Apacer H2\-SL / AP\-*\-2RTM
\- Apacer H1\-SL / AP\-*\-2HTM
\- Apacer H2\-M  / AP\-*\-1RTM
\- Apacer H1\-M  / AP\-*\-1HTM
.EE
.in
.SH OPTIONS
.TP
.I DEVICE
(micro)SD-card device, usually /dev/mmcblk0
.SH EXIT STATUS
.EX
0:     success
255:   invalid commandline-parameters
other: errno of the error
.EE
.SH EXAMPLES
adva-sdcard-smart-get /dev/mmcblk0
.SH AUTHORS
Advamation / Roland Freikamp <support@advamation.de>
.SH SEE ALSO
.BR adva-scard-smart (8),
.BR adva-sdcard-info (8),
adva-sdcard/README.md
